### ISSUE TITLE
Bidirectional inter-app communication ?

### ISSUE THREAD

**Issue by rraallvv** [noln/system-alert-window-example#4]
I'd like to make my own login "service" to allow third parties apps to open the login dialog, and get the user currently logged in. Is that kind of communication posible with a system alert window. Think how Google Play Services opens a dialog on top of the game that's currently running to allow the user to login, and then get back the user id, achievements, etc.
Keep up the good work.

**Comment by noln** [comment]
It's not possible with System Alert Window (SAW) alone, but it is possible with a few additional supporting components to make this work, but it may not be advisable for the reason I'll describe below.

SAW allows you to display UI over the top of other applications, so yes you can display a window over the top of another game or app just like Google Play/Play Games does, but in order to interact with the other app you'll need to implement an API client which will need to be integrated into that other app, and provide it as a Gradle, AAR or JAR dependency.

For instance, if you wanted to provide a login/authentication component for other apps, you could provide a library which could be used by third-party applications that had a method such as `apiClient.login(callback)` which, when called would launch an explicit Intent to your app that will launch an Activity that displays the SAW over the top of the UI. The user then inputs their credentials into the SAW, that would be passed to the service that launched the SAW which could then use the callback provided in the method (I'm just using callback as a basic example, a pub/sub or observable would be a more modern way to do it) call to return that result to the original calling application, with a `success`/`failed` status, user ID or whatever you need to use in-client-app.

**However** there is a drawback with this approach that Google Play Services doesn't suffer from: most modern phones already come with some version of Google Play Services or Play Games already installed. If you create your own version that works in the same way, you will need to prompt the user to install your services app, as they won't already have it preinstalled. It'll also need to be updated separately to the apps that make use of your services component, so you'll need to ensure that if for instance you update your API, that it will be backwards compatible with older apps that use your service, otherwise you could break functionality.

I'd assume that the reason that Google have taken the approach of having a separate component for Play Services is so that they can push updates to the services independently of the apps that use it, as it's actually a more complex deployment situation to manage, given the potential for API mismatching and the long tail of backwards compatibility support.

If I were to implement such a service, I'd offer it as a regular Android library, so the consuming application developer can specify the version that they want to use, and compile the library into their app. Then the login prompt could be an [AlertDialog](https://developer.android.com/reference/android/app/AlertDialog.html) with a custom layout, that you provide in your library.

*Update:*

Another couple of points to consider when using SAW for a service type component:

1. [Malware has given the System Alert Window mechanism a bad name](https://www.nowsecure.com/blog/2017/05/25/android-overlay-malware-system-alert-window-permission/), so it's entirely possible that this feature will be revoked in future versions of Android. Especially given the Android team's recent culling of unofficial API-accessing apps.

2. [Post api level 23, the user must manually flip a switch to enable SAW](https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW). It doesn't work in the same way as other permissions, so the user might be freaked out by having to provide this scary sounding permission with "system" in the name, via an uncommon UI flow.

**Comment by rraallvv** [comment]
Thanks for taking a look into this. So, the reason I'd like to replicate the approach of Google Play Services, is that the app is a mobile wallet for the user to hold in-game currency, but it's not just for games, since the in-game currency is redeemable for real world money (in the form of cryptocurrency). Basically, the users play games and watch ads on our app, then they are rewarded with in-game currency for ad impressions, and can withdraw the cryptocurrency. We have added a couple of games to the app, but will be adding more, some of them will be licensed under GPLv3. So making each game a different app instead of adding them to the main app would allow us to add as many as we want without worrying about the app increasing its size, and also would allow us to add a few GPLv3 games, without having to open source the wallet app, which is mostly a security concern. Thanks again.

**Comment by noln** [comment]
Ah understood, in that case another potential approach could be to provide the login dialog that contained a [Chrome Custom Tab](https://developer.chrome.com/multidevice/android/customtabs). That way you could minimise the amount of code required in the in-app library, as the login logic would all actually be server-side.

The only information you'd need to pass back to the app post-auth would be the `session_id` or whatever `UID` you're using to identify your user.

Way more testable IMO, and doesn't require the user to grant any permissions beyond `INTERNET`.

**Comment by rraallvv** [comment]
I see. You mean something like OAuth, I've only worked with third party authentication platforms like Google, or Twitter. I haven't developed my own OAuth server yet, but I can give it a try. Thanks for your suggestion.
